signup:
    path:     /signup
    defaults: { _controller: TipmytipBundle:Signup:index }

location:
    path:     /location
    defaults: { _controller: TipmytipBundle:Signup:location }

city:
    path:     /city/{country_id}
    defaults: { _controller: TipmytipBundle:Signup:city }

createaccount:
    path:     /createaccount
    defaults: { _controller: TipmytipBundle:Signup:create }

landing_page:
    path:     /
    defaults: { _controller: TipmytipBundle:Page:landingpage }
    
landing_page_thank_you:
    path:     /thank-you
    defaults: { _controller: TipmytipBundle:Page:landingpagethankyou }
