# src/TipmytipBundle/Resources/config/doctrine/Category.orm.yml
TipmytipBundle\Entity\Category:
  type: entity
  table: category
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255