# src/TipmytipBundle/Resources/config/doctrine/Location.orm.yml
TipmytipBundle\Entity\Location:
  type: entity
  table: location
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    latitude:
      type: string
      length: 255
    longitude:
      type: string
      length: 255
    name:
      type: string
      length: 255
    available:
      type: boolean
  oneToMany:
    questions:
      targetEntity: Question
      mappedBy: location
      onDelete: CASCADE
    users:
      targetEntity: User
      mappedBy: location
      onDelete: CASCADE
  manyToOne:
    country:
      targetEntity: Country
      inversedBy: locations
      joinColumn:
        name: country_id
        referencedColumnName: id
        onDelete: CASCADE