# src/TipmytipBundle/Resources/config/doctrine/Message.orm.yml
TipmytipBundle\Entity\Message:
  type: entity
  table: message
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    text:
      type: string
      length: 255
    date:
      type: datetime
    read_date:
      type: datetime