# src/TipmytipBundle/Resources/config/doctrine/Thankyou.orm.yml
TipmytipBundle\Entity\Thankyou:
  type: entity
  table: thankyou
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    level:
      type: string
      length: 255
    date:
      type: date